### PR TITLE
allow setting of Deluge address via environment variable DELUGE_HOST

### PR DESCRIPTION
**Pull request by jangrewe**
add Dockerfile

Run it like this:
```
docker run -e "DELUGE_HOST=172.17.0.1" -v /etc/deluge:/root/.config/deluge/ -p 9354:9354 registry.example.com/deluge_exporter:latest
```

### CODE REVIEW

**Comment by tobbez** [comment]
Code looks good as far as I can tell (don't use docker much).

Please split the commit into one for each distinct change (one for DELUGE_HOST support, one for the Dockerfile).

Or would you prefer if I just split it myself and merged it?

**Comment by jangrewe** [comment]
You can split it if you want, i didn't plan on maintaining an long term fork. ;-)
Could you also sign up with hub.docker.com to have this image built automatically on push, so that there's an official one?

And a bit off-topic, but: what do you think of merging all the `deluge_libtorrent_*_download_bytes_total` metrics into a single `deluge_libtorrent_download_bytes_total{type="*"}` metric (same for the upload metrics, of course), so using labels instead of separate metrics? I guess that's a bit more Prometheus-style ;-)

**Comment by tobbez** [comment]
There's now an image on docker hub.

The upload and download metrics have also been consolidated (ffa8b294edee1b71db9c2f74e22e1795a2979505).

**Comment by jangrewe** [comment]
Great, thank you!

**Pull request closed without merging**
